# Generated by ./update.sh - do not update manually!
# Last updated: 2026-01-08
{fetchurl}: {
  napcat = {
    version = "4.10.10";
    src = fetchurl {
      url = "https://github.com/NapNeko/NapCatQQ/releases/download/v4.10.10/NapCat.Shell.zip";
      hash = "sha256-+TBDJ9No3+7rQPacic3L6VY7+ylgcd+hcBVbiBV4miQ=";
    };
  };
  qq = {
    aarch64-linux = {
      version = "3.2.20-40990";
      src = fetchurl {
        url = "https://dldir1.qq.com/qqfile/qq/QQNT/ec800879/linuxqq_3.2.20-40990_arm64.deb";
        hash = "sha256-m90k4S0BAA3R4alRl+1ZfLK3q35LnCVBMUOcJpALIYU=";
      };
    };
    x86_64-linux = {
      version = "3.2.20-40990";
      src = fetchurl {
        url = "https://dldir1.qq.com/qqfile/qq/QQNT/ec800879/linuxqq_3.2.20-40990_amd64.deb";
        hash = "sha256-PIq2FPB+LpnyfzE51o9eulw93/BofPrlU+PqUyYlh2M=";
      };
    };
  };
}
