#! /usr/bin/env nix-shell
#! nix-shell -i bash --pure --keep GITHUB_TOKEN -p nix git curl cacert nix-prefetch-git jq

# Based on https://github.com/NixOS/nixpkgs/blob/nixos-25.11/pkgs/by-name/qq/qq/update.sh

set -euo pipefail

cd $(readlink -e $(dirname "${BASH_SOURCE[0]}"))
 
# qq
qq_version="3.2.20-40990"
qq_aarch64_url="https://dldir1.qq.com/qqfile/qq/QQNT/ec800879/linuxqq_3.2.20-40990_arm64.deb"
qq_x86_64_url="https://dldir1.qq.com/qqfile/qq/QQNT/ec800879/linuxqq_3.2.20-40990_amd64.deb"

qq_aarch64_hash="sha256-m90k4S0BAA3R4alRl+1ZfLK3q35LnCVBMUOcJpALIYU="
qq_x86_64_hash="sha256-PIq2FPB+LpnyfzE51o9eulw93/BofPrlU+PqUyYlh2M="
 
# napcat
napcat_payload=$(curl https://api.github.com/repos/NapNeko/NapCatQQ/releases/latest)
napcat_version=$(jq -r .tag_name <<< "$napcat_payload" | sed 's/^v//')
napcat_url=$(jq -r '.assets[] | select(.name == "NapCat.Shell.zip") | .browser_download_url' <<< "$napcat_payload")
napcat_hash=$(nix-prefetch-url $napcat_url)
napcat_hash=$(nix --extra-experimental-features nix-command hash convert --to sri --hash-algo sha256 "$napcat_hash")

cat >sources.nix <<EOF
# Generated by ./update.sh - do not update manually!
# Last updated: $(date +%F)
{ fetchurl }:
{
  napcat = {
    version = "$napcat_version";
    src = fetchurl {
      url = "$napcat_url";
      hash = "$napcat_hash";
    };
  };
  qq = {
    aarch64-linux = {
      version = "$qq_version";
      src = fetchurl {
        url = "$qq_aarch64_url";
        hash = "$qq_aarch64_hash";
      };
    };
    x86_64-linux = {
      version = "$qq_version";
      src = fetchurl {
        url = "$qq_x86_64_url";
        hash = "$qq_x86_64_hash";
      };
    };
  };
}
EOF