name: "Build and release"
on:
    push:
        tags:
            - "v*"
    workflow_dispatch:
jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: cachix/install-nix-action@v27
              with:
                  github_access_token: ${{ secrets.GITHUB_TOKEN }}
            - name: Build
              run: nix bundle --bundler github:ralismark/nix-appimage .#napcat

            - name: Name | Name Package
              run: |
                  TAG_NAME="${GITHUB_REF#refs/tags/}"
                  echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
                  cp -L napcat.AppImage napcat_${TAG_NAME}.AppImage
                  ls -la
            - name: Release
              uses: softprops/action-gh-release@v2
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  files: napcat.AppImage
