name: "Build artifact"
on:
    workflow_dispatch:
jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: cachix/install-nix-action@v27
              with:
                  github_access_token: ${{ secrets.GITHUB_TOKEN }}
            - name: Build
              run: nix bundle --bundler github:ralismark/nix-appimage .#napcat
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: napcat.AppImage
                  path: napcat.AppImage
