name: "Test"
on:
    pull_request:
    push:
jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: cachix/install-nix-action@v27
              with:
                  github_access_token: ${{ secrets.GITHUB_TOKEN }}
            - run: nix bundle --out-link ./output --bundler github:ralismark/nix-appimage .#napcat
            - uses: actions/upload-artifact@v4
              with:
                  name: napcat.AppImage
                  path: ./output
